server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 126070257762-hi0pgo39fdumdcvioebdsp9fcdr6vklr.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
